"""
Django settings for restaurant_ecommerce project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from django.contrib.auth.models import User
from urllib.parse import urlparse

from django.core.exceptions import ImproperlyConfigured

try:
    from dotenv import load_dotenv
except Exception:  # pragma: no cover
    load_dotenv = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env (recommended for local dev)
if load_dotenv:
    load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!


def _env_bool(name: str, default: bool = False) -> bool:
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "t", "yes", "y", "on"}


def _env_csv(name: str) -> list[str]:
    raw = os.getenv(name, "")
    return [part.strip() for part in raw.split(",") if part.strip()]


def _hostname_from_any(value: str) -> str | None:
    value = (value or "").strip()
    if not value:
        return None

    if "://" in value:
        parsed = urlparse(value)
        netloc = (parsed.netloc or "").strip()
        if not netloc:
            return None
        netloc = netloc.split("@")[-1]
        return (netloc.split(":")[0] or "").strip() or None

    value = value.split("/")[0]
    return (value.split(":")[0] or "").strip() or None


SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-6%k=ehoz*k%ricx0!wd7@c@&w*^%=-t6j6-_vburnyp%b(-mty",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

_allowed_hosts: set[str] = set(_env_csv("ALLOWED_HOSTS"))

# Platform-provided external hostnames (Railway / legacy Render)
_railway_public_domain = _hostname_from_any(os.getenv("RAILWAY_PUBLIC_DOMAIN") or "")
_railway_url_host = _hostname_from_any(os.getenv("RAILWAY_URL") or "")
_render_external_hostname = _hostname_from_any(os.getenv("RENDER_EXTERNAL_HOSTNAME") or "")

_is_railway = bool(_railway_public_domain or _railway_url_host)

for _host in (_railway_public_domain, _railway_url_host, _render_external_hostname):
    if _host:
        _allowed_hosts.add(_host)

# Optional fallback for this project’s default Railway domain
_allowed_hosts.add("foodora-production-110c.up.railway.app")

# CSRF trusted origins
# Note: Django's CSRF origin checks can trigger even with DEBUG=True.
# So we derive trusted origins from known deploy hostnames regardless of DEBUG.
_csrf_trusted: set[str] = set(_env_csv("CSRF_TRUSTED_ORIGINS"))
for _host in _allowed_hosts:
    if _host:
        _csrf_trusted.add(f"https://{_host}")
if _csrf_trusted:
    CSRF_TRUSTED_ORIGINS = sorted(_csrf_trusted)

if DEBUG:
    ALLOWED_HOSTS = ["*"]
else:
    if not _allowed_hosts:
        raise ImproperlyConfigured(
            "ALLOWED_HOSTS must be set in production (e.g. set ALLOWED_HOSTS or RAILWAY_PUBLIC_DOMAIN)."
        )
    ALLOWED_HOSTS = sorted(_allowed_hosts)

if not DEBUG and SECRET_KEY.startswith("django-insecure") and not os.getenv("SECRET_KEY"):
    raise ImproperlyConfigured("SECRET_KEY must be set in production.")

if not User.objects.filter(username="admin").exists():
    User.objects.create_superuser(
        username="admin",
        email="admin@gmail.com",
        password="Admin@123"
    )

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Project apps
    'apps.accounts_app.apps.AccountsConfig',
    'apps.menu_app.apps.MenuConfig',
    'apps.cart_app.apps.CartConfig',
    'apps.orders_app.apps.OrdersConfig',
    'apps.payments_app.apps.PaymentsConfig',
    'apps.reviews_app.apps.ReviewsConfig',
    'apps.adminpanel_app.apps.AdminPanelConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'restaurant_ecommerce.middleware.PathBasedSessionCookieMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'restaurant_ecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # Project context
                'apps.cart_app.context_processors.cart_summary',
                'apps.menu_app.context_processors.nav_categories',
                'apps.accounts_app.context_processors.auth_forms',
            ],
        },
    },
]

WSGI_APPLICATION = 'restaurant_ecommerce.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

_sqlite_default_db = {
    'ENGINE': 'django.db.backends.sqlite3',
    'NAME': BASE_DIR / 'db.sqlite3',
}

DATABASES = {'default': _sqlite_default_db}

_database_url = (os.getenv("DATABASE_URL") or "").strip()
if _database_url:
    try:
        import dj_database_url
    except ImportError as exc:  # pragma: no cover
        raise ImproperlyConfigured(
            "DATABASE_URL is set but dj-database-url is not installed. Add it to requirements.txt."
        ) from exc

    DATABASES['default'] = dj_database_url.parse(
        _database_url,
        conn_max_age=int(os.getenv("DB_CONN_MAX_AGE", "600")),
    )


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Auth
AUTH_USER_MODEL = 'accounts.User'
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'menu:home'
LOGOUT_REDIRECT_URL = 'menu:home'

# Custom hidden admin panel
PRIVATE_ADMIN_EMAIL = (os.getenv('PRIVATE_ADMIN_EMAIL') or '').strip()
PRIVATE_ADMIN_PASSWORD = os.getenv('PRIVATE_ADMIN_PASSWORD') or ''
PRIVATE_ADMIN_URL_PREFIX = 'private-admin/'

# Razorpay (test mode) — keep secrets in environment variables
RAZORPAY_KEY_ID = (os.getenv('RAZORPAY_KEY_ID') or '').strip()
RAZORPAY_KEY_SECRET = (os.getenv('RAZORPAY_KEY_SECRET') or '').strip()

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Security / proxy settings (Railway runs behind a proxy)
if (not DEBUG) or _is_railway:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = _env_bool("SECURE_SSL_REDIRECT", default=True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
