# Generated by Django 5.2.14 on 2026-06-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_deliverypincode_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('MENU', 'Menu'), ('CATERING', 'Catering Menu')], default='MENU', max_length=20),
        ),
    ]
