# Generated by Django 5.2.15 on 2026-06-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_addon_orderitemaddon'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_hero',
            field=models.BooleanField(default=False, verbose_name='Show in Hero Section'),
        ),
    ]
