# Generated by Django 5.2.12 on 2026-03-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='spice_level_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
