# Generated by Django 5.2.12 on 2026-03-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_scheduled_time_order_special_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='spice_level',
            field=models.CharField(blank=True, choices=[('KIDS', 'Kids (mild)'), ('MILD', 'Mild'), ('MEDIUM', 'Medium'), ('SPICY', 'Spicy')], max_length=10),
        ),
    ]
